CREATE TABLE T1 (A INT);
INSERT INTO T1 VALUES (3), (1), (4);
CREATE TABLE T2 (A INT);
INSERT INTO T2 VALUES (2), (4), (3);

T1과 T2의 합집합(중복 제거)을 구한 후 A 컬럼 기준 내림차순 정렬
SELECT A FROM T1 UNION SELECT A FROM T2 ORDER BY A DESC;