CREATE TABLE Table_A(COL1 INTEGER, COL2 INTEGER);
CREATE TABLE Table_B(COL1 INTEGER, COL2 INTEGER);

INSERT INTO Table_A(COL1, COL2) VALUES(1, 2);
INSERT INTO Table_A(COL1, COL2) VALUES(1, 2);
INSERT INTO Table_A(COL1, COL2) VALUES(1, 3);

INSERT INTO Table_B(COL1, COL2) VALUES(1, 2);
INSERT INTO Table_B(COL1, COL2) VALUES(1, 4);
INSERT INTO Table_B(COL1, COL2) VALUES(1, 5);

Table_A의 중복 제거 결과와 Table_B의 결과를 합집합한 후 COL2 내림차순 정렬
SELECT DISTINCT COL1, COL2 FROM Table_A
UNION
SELECT COL1, COL2 FROM Table_B ORDER BY COL2 DESC;
